# Generated by Django 5.0.1 on 2024-01-17 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcarddesafio_desafio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desafio',
            new_name='Challenge',
        ),
        migrations.RenameModel(
            old_name='FlashcardDesafio',
            new_name='FlashcardChallenge',
        ),
    ]
